# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\repo\Aptect\Verizon\Workproduct\EON-IOT\outage_browser\outage_browser.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1350, 834)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_3.setMargin(3)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.job_data_line_edit = QtGui.QLineEdit(self.centralWidget)
        self.job_data_line_edit.setObjectName(_fromUtf8("job_data_line_edit"))
        self.horizontalLayout_2.addWidget(self.job_data_line_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.parse_job_data = QtGui.QPushButton(self.centralWidget)
        self.parse_job_data.setObjectName(_fromUtf8("parse_job_data"))
        self.horizontalLayout.addWidget(self.parse_job_data)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(-1, 6, -1, 6)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 5, 1, 1)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 6, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 7, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 8, 1, 1)
        self.job_number_line_edit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.job_number_line_edit.sizePolicy().hasHeightForWidth())
        self.job_number_line_edit.setSizePolicy(sizePolicy)
        self.job_number_line_edit.setObjectName(_fromUtf8("job_number_line_edit"))
        self.gridLayout.addWidget(self.job_number_line_edit, 1, 0, 1, 1)
        self.num_customer_line_edit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_customer_line_edit.sizePolicy().hasHeightForWidth())
        self.num_customer_line_edit.setSizePolicy(sizePolicy)
        self.num_customer_line_edit.setMinimumSize(QtCore.QSize(40, 0))
        self.num_customer_line_edit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.num_customer_line_edit.setObjectName(_fromUtf8("num_customer_line_edit"))
        self.gridLayout.addWidget(self.num_customer_line_edit, 1, 1, 1, 1)
        self.time_received_line_edit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_received_line_edit.sizePolicy().hasHeightForWidth())
        self.time_received_line_edit.setSizePolicy(sizePolicy)
        self.time_received_line_edit.setObjectName(_fromUtf8("time_received_line_edit"))
        self.gridLayout.addWidget(self.time_received_line_edit, 1, 2, 1, 1)
        self.time_complete_line_edit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_complete_line_edit.sizePolicy().hasHeightForWidth())
        self.time_complete_line_edit.setSizePolicy(sizePolicy)
        self.time_complete_line_edit.setObjectName(_fromUtf8("time_complete_line_edit"))
        self.gridLayout.addWidget(self.time_complete_line_edit, 1, 3, 1, 1)
        self.address_line_edit = QtGui.QLineEdit(self.frame)
        self.address_line_edit.setObjectName(_fromUtf8("address_line_edit"))
        self.gridLayout.addWidget(self.address_line_edit, 1, 4, 1, 1)
        self.city_state_line_edit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_state_line_edit.sizePolicy().hasHeightForWidth())
        self.city_state_line_edit.setSizePolicy(sizePolicy)
        self.city_state_line_edit.setObjectName(_fromUtf8("city_state_line_edit"))
        self.gridLayout.addWidget(self.city_state_line_edit, 1, 5, 1, 1)
        self.feeder_combo_box = QtGui.QComboBox(self.frame)
        self.feeder_combo_box.setObjectName(_fromUtf8("feeder_combo_box"))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.feeder_combo_box.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.feeder_combo_box, 1, 6, 1, 1)
        self.lat_lon_line_edit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_lon_line_edit.sizePolicy().hasHeightForWidth())
        self.lat_lon_line_edit.setSizePolicy(sizePolicy)
        self.lat_lon_line_edit.setMinimumSize(QtCore.QSize(180, 0))
        self.lat_lon_line_edit.setObjectName(_fromUtf8("lat_lon_line_edit"))
        self.gridLayout.addWidget(self.lat_lon_line_edit, 1, 7, 1, 1)
        self.ms_plate_line_edit = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ms_plate_line_edit.sizePolicy().hasHeightForWidth())
        self.ms_plate_line_edit.setSizePolicy(sizePolicy)
        self.ms_plate_line_edit.setMinimumSize(QtCore.QSize(60, 0))
        self.ms_plate_line_edit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.ms_plate_line_edit.setObjectName(_fromUtf8("ms_plate_line_edit"))
        self.gridLayout.addWidget(self.ms_plate_line_edit, 1, 8, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.centralWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtGui.QGroupBox(self.splitter)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_2.setVerticalSpacing(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.get_utility_assets_by_feeder = QtGui.QPushButton(self.groupBox)
        self.get_utility_assets_by_feeder.setObjectName(_fromUtf8("get_utility_assets_by_feeder"))
        self.horizontalLayout_3.addWidget(self.get_utility_assets_by_feeder)
        self.enable_asset_sort = QtGui.QCheckBox(self.groupBox)
        self.enable_asset_sort.setChecked(True)
        self.enable_asset_sort.setObjectName(_fromUtf8("enable_asset_sort"))
        self.horizontalLayout_3.addWidget(self.enable_asset_sort)
        self.clear_utility_selection = QtGui.QPushButton(self.groupBox)
        self.clear_utility_selection.setMaximumSize(QtCore.QSize(40, 18))
        self.clear_utility_selection.setObjectName(_fromUtf8("clear_utility_selection"))
        self.horizontalLayout_3.addWidget(self.clear_utility_selection)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.page_load_label = QtGui.QLabel(self.groupBox)
        self.page_load_label.setObjectName(_fromUtf8("page_load_label"))
        self.horizontalLayout_3.addWidget(self.page_load_label)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.assets_table_widget = QtGui.QTableWidget(self.groupBox)
        self.assets_table_widget.setObjectName(_fromUtf8("assets_table_widget"))
        self.assets_table_widget.setColumnCount(0)
        self.assets_table_widget.setRowCount(0)
        self.gridLayout_2.addWidget(self.assets_table_widget, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.splitter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_5.setVerticalSpacing(3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.collect_onts_pushbutton = QtGui.QPushButton(self.groupBox_4)
        self.collect_onts_pushbutton.setObjectName(_fromUtf8("collect_onts_pushbutton"))
        self.horizontalLayout_6.addWidget(self.collect_onts_pushbutton)
        self.enable_collect_sort = QtGui.QCheckBox(self.groupBox_4)
        self.enable_collect_sort.setChecked(True)
        self.enable_collect_sort.setObjectName(_fromUtf8("enable_collect_sort"))
        self.horizontalLayout_6.addWidget(self.enable_collect_sort)
        self.clear_collect_select = QtGui.QPushButton(self.groupBox_4)
        self.clear_collect_select.setMaximumSize(QtCore.QSize(40, 18))
        self.clear_collect_select.setObjectName(_fromUtf8("clear_collect_select"))
        self.horizontalLayout_6.addWidget(self.clear_collect_select)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.clear_collection_pushbutton = QtGui.QPushButton(self.groupBox_4)
        self.clear_collection_pushbutton.setObjectName(_fromUtf8("clear_collection_pushbutton"))
        self.horizontalLayout_6.addWidget(self.clear_collection_pushbutton)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.ont_collection_table_widget = QtGui.QTableWidget(self.groupBox_4)
        self.ont_collection_table_widget.setObjectName(_fromUtf8("ont_collection_table_widget"))
        self.ont_collection_table_widget.setColumnCount(0)
        self.ont_collection_table_widget.setRowCount(0)
        self.gridLayout_5.addWidget(self.ont_collection_table_widget, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.splitter_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_3.setPalette(palette)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_6.setVerticalSpacing(3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 1, 1, 1)
        self.ont_lat_lon_line_edit = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ont_lat_lon_line_edit.sizePolicy().hasHeightForWidth())
        self.ont_lat_lon_line_edit.setSizePolicy(sizePolicy)
        self.ont_lat_lon_line_edit.setMinimumSize(QtCore.QSize(180, 0))
        self.ont_lat_lon_line_edit.setObjectName(_fromUtf8("ont_lat_lon_line_edit"))
        self.gridLayout_4.addWidget(self.ont_lat_lon_line_edit, 1, 0, 1, 1)
        self.ont_radius_line_edit = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ont_radius_line_edit.sizePolicy().hasHeightForWidth())
        self.ont_radius_line_edit.setSizePolicy(sizePolicy)
        self.ont_radius_line_edit.setMinimumSize(QtCore.QSize(40, 0))
        self.ont_radius_line_edit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.ont_radius_line_edit.setObjectName(_fromUtf8("ont_radius_line_edit"))
        self.gridLayout_4.addWidget(self.ont_radius_line_edit, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_4)
        self.enable_ont_sort = QtGui.QCheckBox(self.groupBox_3)
        self.enable_ont_sort.setChecked(True)
        self.enable_ont_sort.setObjectName(_fromUtf8("enable_ont_sort"))
        self.horizontalLayout_5.addWidget(self.enable_ont_sort)
        self.clear_ont_select = QtGui.QPushButton(self.groupBox_3)
        self.clear_ont_select.setMaximumSize(QtCore.QSize(40, 18))
        self.clear_ont_select.setObjectName(_fromUtf8("clear_ont_select"))
        self.horizontalLayout_5.addWidget(self.clear_ont_select)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.ont_area_load_label = QtGui.QLabel(self.groupBox_3)
        self.ont_area_load_label.setObjectName(_fromUtf8("ont_area_load_label"))
        self.horizontalLayout_5.addWidget(self.ont_area_load_label)
        self.get_onts_in_area = QtGui.QPushButton(self.groupBox_3)
        self.get_onts_in_area.setObjectName(_fromUtf8("get_onts_in_area"))
        self.horizontalLayout_5.addWidget(self.get_onts_in_area)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.ont_table_widget = QtGui.QTableWidget(self.groupBox_3)
        self.ont_table_widget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.ont_table_widget.setObjectName(_fromUtf8("ont_table_widget"))
        self.ont_table_widget.setColumnCount(0)
        self.ont_table_widget.setRowCount(0)
        self.gridLayout_6.addWidget(self.ont_table_widget, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.splitter_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.groupBox_2.setPalette(palette)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.get_raw_alarms_4_onts = QtGui.QPushButton(self.groupBox_2)
        self.get_raw_alarms_4_onts.setObjectName(_fromUtf8("get_raw_alarms_4_onts"))
        self.horizontalLayout_4.addWidget(self.get_raw_alarms_4_onts)
        self.enable_raw_sort = QtGui.QCheckBox(self.groupBox_2)
        self.enable_raw_sort.setChecked(True)
        self.enable_raw_sort.setObjectName(_fromUtf8("enable_raw_sort"))
        self.horizontalLayout_4.addWidget(self.enable_raw_sort)
        self.alarm_load_label = QtGui.QLabel(self.groupBox_2)
        self.alarm_load_label.setObjectName(_fromUtf8("alarm_load_label"))
        self.horizontalLayout_4.addWidget(self.alarm_load_label)
        self.filter_for_duration = QtGui.QCheckBox(self.groupBox_2)
        self.filter_for_duration.setObjectName(_fromUtf8("filter_for_duration"))
        self.horizontalLayout_4.addWidget(self.filter_for_duration)
        self.export_selected_alarms_pushbutton = QtGui.QPushButton(self.groupBox_2)
        self.export_selected_alarms_pushbutton.setObjectName(_fromUtf8("export_selected_alarms_pushbutton"))
        self.horizontalLayout_4.addWidget(self.export_selected_alarms_pushbutton)
        self.export_directory_line_edit = QtGui.QLineEdit(self.groupBox_2)
        self.export_directory_line_edit.setObjectName(_fromUtf8("export_directory_line_edit"))
        self.horizontalLayout_4.addWidget(self.export_directory_line_edit)
        self.assign_to_assets = QtGui.QPushButton(self.groupBox_2)
        self.assign_to_assets.setObjectName(_fromUtf8("assign_to_assets"))
        self.horizontalLayout_4.addWidget(self.assign_to_assets)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.restrict_to_timespan_checkbox = QtGui.QCheckBox(self.groupBox_2)
        self.restrict_to_timespan_checkbox.setChecked(True)
        self.restrict_to_timespan_checkbox.setObjectName(_fromUtf8("restrict_to_timespan_checkbox"))
        self.horizontalLayout_4.addWidget(self.restrict_to_timespan_checkbox)
        self.time_span_window = QtGui.QLineEdit(self.groupBox_2)
        self.time_span_window.setMaximumSize(QtCore.QSize(40, 16777215))
        self.time_span_window.setObjectName(_fromUtf8("time_span_window"))
        self.horizontalLayout_4.addWidget(self.time_span_window)
        self.restrict_to_radius_checkbox = QtGui.QCheckBox(self.groupBox_2)
        self.restrict_to_radius_checkbox.setChecked(True)
        self.restrict_to_radius_checkbox.setObjectName(_fromUtf8("restrict_to_radius_checkbox"))
        self.horizontalLayout_4.addWidget(self.restrict_to_radius_checkbox)
        self.export_kml = QtGui.QPushButton(self.groupBox_2)
        self.export_kml.setObjectName(_fromUtf8("export_kml"))
        self.horizontalLayout_4.addWidget(self.export_kml)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.alarms_table_widget = QtGui.QTableWidget(self.groupBox_2)
        self.alarms_table_widget.setObjectName(_fromUtf8("alarms_table_widget"))
        self.alarms_table_widget.setColumnCount(0)
        self.alarms_table_widget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.alarms_table_widget)
        self.gridLayout_3.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.operation_progress_bar = QtGui.QProgressBar(self.centralWidget)
        self.operation_progress_bar.setProperty("value", 24)
        self.operation_progress_bar.setObjectName(_fromUtf8("operation_progress_bar"))
        self.horizontalLayout_8.addWidget(self.operation_progress_bar)
        self.stop_pushbutton = QtGui.QPushButton(self.centralWidget)
        self.stop_pushbutton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.stop_pushbutton.setObjectName(_fromUtf8("stop_pushbutton"))
        self.horizontalLayout_8.addWidget(self.stop_pushbutton)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.centralWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox_5.setPalette(palette)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.mark_raw_events_pushbutton = QtGui.QPushButton(self.groupBox_5)
        self.mark_raw_events_pushbutton.setObjectName(_fromUtf8("mark_raw_events_pushbutton"))
        self.horizontalLayout_10.addWidget(self.mark_raw_events_pushbutton)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.dump_raw_event_pushbutton = QtGui.QPushButton(self.groupBox_5)
        self.dump_raw_event_pushbutton.setObjectName(_fromUtf8("dump_raw_event_pushbutton"))
        self.horizontalLayout_10.addWidget(self.dump_raw_event_pushbutton)
        self.find_alarm_files_bushbutton = QtGui.QPushButton(self.groupBox_5)
        self.find_alarm_files_bushbutton.setObjectName(_fromUtf8("find_alarm_files_bushbutton"))
        self.horizontalLayout_10.addWidget(self.find_alarm_files_bushbutton)
        self.label_16 = QtGui.QLabel(self.groupBox_5)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_10.addWidget(self.label_16)
        self.ont_search_string_text = QtGui.QLineEdit(self.groupBox_5)
        self.ont_search_string_text.setObjectName(_fromUtf8("ont_search_string_text"))
        self.horizontalLayout_10.addWidget(self.ont_search_string_text)
        self.label_14 = QtGui.QLabel(self.groupBox_5)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_10.addWidget(self.label_14)
        self.start_date_time_edit = QtGui.QDateTimeEdit(self.groupBox_5)
        self.start_date_time_edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 5, 10), QtCore.QTime(0, 0, 0)))
        self.start_date_time_edit.setCalendarPopup(True)
        self.start_date_time_edit.setObjectName(_fromUtf8("start_date_time_edit"))
        self.horizontalLayout_10.addWidget(self.start_date_time_edit)
        self.label_15 = QtGui.QLabel(self.groupBox_5)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_10.addWidget(self.label_15)
        self.end_date_time_edit = QtGui.QDateTimeEdit(self.groupBox_5)
        self.end_date_time_edit.setDateTime(QtCore.QDateTime(QtCore.QDate(2015, 5, 31), QtCore.QTime(23, 29, 0)))
        self.end_date_time_edit.setTime(QtCore.QTime(23, 29, 0))
        self.end_date_time_edit.setCalendarPopup(True)
        self.end_date_time_edit.setObjectName(_fromUtf8("end_date_time_edit"))
        self.horizontalLayout_10.addWidget(self.end_date_time_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.clear_raw_events_pushbutton = QtGui.QPushButton(self.groupBox_5)
        self.clear_raw_events_pushbutton.setObjectName(_fromUtf8("clear_raw_events_pushbutton"))
        self.horizontalLayout_9.addWidget(self.clear_raw_events_pushbutton)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.label_13 = QtGui.QLabel(self.groupBox_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_9.addWidget(self.label_13)
        self.alarm_files_combo_box = QtGui.QComboBox(self.groupBox_5)
        self.alarm_files_combo_box.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.alarm_files_combo_box.setObjectName(_fromUtf8("alarm_files_combo_box"))
        self.horizontalLayout_9.addWidget(self.alarm_files_combo_box)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.gridLayout_3.addWidget(self.groupBox_5, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1350, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menuBar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menuBar)
        self.browser_status_bar = QtGui.QStatusBar(MainWindow)
        self.browser_status_bar.setObjectName(_fromUtf8("browser_status_bar"))
        MainWindow.setStatusBar(self.browser_status_bar)
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.menuSettings.addAction(self.actionPreferences)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_10.setText(_translate("MainWindow", "Job Data", None))
        self.parse_job_data.setText(_translate("MainWindow", "Parse and Load", None))
        self.label_5.setText(_translate("MainWindow", "Job Number", None))
        self.label_6.setText(_translate("MainWindow", "# Cust", None))
        self.label_3.setText(_translate("MainWindow", "Time Received", None))
        self.label_4.setText(_translate("MainWindow", "Time Completed", None))
        self.label_7.setText(_translate("MainWindow", "Address", None))
        self.label_9.setText(_translate("MainWindow", "City, State, Zip", None))
        self.label.setText(_translate("MainWindow", "Feeder", None))
        self.label_2.setText(_translate("MainWindow", "Lat, Lon", None))
        self.label_8.setText(_translate("MainWindow", "MS Plate", None))
        self.job_number_line_edit.setText(_translate("MainWindow", "WE15014995", None))
        self.time_received_line_edit.setText(_translate("MainWindow", "05/11/2015 17:02", None))
        self.time_complete_line_edit.setText(_translate("MainWindow", "5/11/2015  5:02:00 PM", None))
        self.address_line_edit.setText(_translate("MainWindow", "141 DOGWOOD RD", None))
        self.city_state_line_edit.setText(_translate("MainWindow", "CORTLANDT TOWN", None))
        self.feeder_combo_box.setItemText(0, _translate("MainWindow", "10U2", None))
        self.feeder_combo_box.setItemText(1, _translate("MainWindow", "13W78", None))
        self.feeder_combo_box.setItemText(2, _translate("MainWindow", "14U1", None))
        self.feeder_combo_box.setItemText(3, _translate("MainWindow", "14W12", None))
        self.feeder_combo_box.setItemText(4, _translate("MainWindow", "19U2", None))
        self.feeder_combo_box.setItemText(5, _translate("MainWindow", "20U2", None))
        self.feeder_combo_box.setItemText(6, _translate("MainWindow", "22U1", None))
        self.feeder_combo_box.setItemText(7, _translate("MainWindow", "22U2", None))
        self.feeder_combo_box.setItemText(8, _translate("MainWindow", "22U3", None))
        self.feeder_combo_box.setItemText(9, _translate("MainWindow", "22U4", None))
        self.feeder_combo_box.setItemText(10, _translate("MainWindow", "23U2", None))
        self.feeder_combo_box.setItemText(11, _translate("MainWindow", "23U3", None))
        self.feeder_combo_box.setItemText(12, _translate("MainWindow", "24U1", None))
        self.feeder_combo_box.setItemText(13, _translate("MainWindow", "24U2", None))
        self.feeder_combo_box.setItemText(14, _translate("MainWindow", "24U3", None))
        self.feeder_combo_box.setItemText(15, _translate("MainWindow", "25U4", None))
        self.feeder_combo_box.setItemText(16, _translate("MainWindow", "28U1", None))
        self.feeder_combo_box.setItemText(17, _translate("MainWindow", "39U1", None))
        self.feeder_combo_box.setItemText(18, _translate("MainWindow", "39U2", None))
        self.feeder_combo_box.setItemText(19, _translate("MainWindow", "39U3", None))
        self.feeder_combo_box.setItemText(20, _translate("MainWindow", "39U4", None))
        self.feeder_combo_box.setItemText(21, _translate("MainWindow", "40U1", None))
        self.feeder_combo_box.setItemText(22, _translate("MainWindow", "40U3", None))
        self.feeder_combo_box.setItemText(23, _translate("MainWindow", "40U4", None))
        self.feeder_combo_box.setItemText(24, _translate("MainWindow", "411", None))
        self.feeder_combo_box.setItemText(25, _translate("MainWindow", "48U1", None))
        self.feeder_combo_box.setItemText(26, _translate("MainWindow", "48U2", None))
        self.feeder_combo_box.setItemText(27, _translate("MainWindow", "48U3", None))
        self.feeder_combo_box.setItemText(28, _translate("MainWindow", "48U4", None))
        self.feeder_combo_box.setItemText(29, _translate("MainWindow", "59U1", None))
        self.feeder_combo_box.setItemText(30, _translate("MainWindow", "59U2", None))
        self.feeder_combo_box.setItemText(31, _translate("MainWindow", "59U3", None))
        self.feeder_combo_box.setItemText(32, _translate("MainWindow", "60U2", None))
        self.feeder_combo_box.setItemText(33, _translate("MainWindow", "60U3", None))
        self.feeder_combo_box.setItemText(34, _translate("MainWindow", "60U4", None))
        self.feeder_combo_box.setItemText(35, _translate("MainWindow", "64U1", None))
        self.feeder_combo_box.setItemText(36, _translate("MainWindow", "64U2", None))
        self.feeder_combo_box.setItemText(37, _translate("MainWindow", "64U3", None))
        self.feeder_combo_box.setItemText(38, _translate("MainWindow", "72U1", None))
        self.feeder_combo_box.setItemText(39, _translate("MainWindow", "72U2", None))
        self.feeder_combo_box.setItemText(40, _translate("MainWindow", "73U1", None))
        self.feeder_combo_box.setItemText(41, _translate("MainWindow", "77U1", None))
        self.feeder_combo_box.setItemText(42, _translate("MainWindow", "77U2", None))
        self.feeder_combo_box.setItemText(43, _translate("MainWindow", "77U3", None))
        self.feeder_combo_box.setItemText(44, _translate("MainWindow", "77U4", None))
        self.feeder_combo_box.setItemText(45, _translate("MainWindow", "84U3", None))
        self.feeder_combo_box.setItemText(46, _translate("MainWindow", "85U1", None))
        self.feeder_combo_box.setItemText(47, _translate("MainWindow", "85U2", None))
        self.feeder_combo_box.setItemText(48, _translate("MainWindow", "85U3", None))
        self.feeder_combo_box.setItemText(49, _translate("MainWindow", "85U4", None))
        self.feeder_combo_box.setItemText(50, _translate("MainWindow", "87U1", None))
        self.feeder_combo_box.setItemText(51, _translate("MainWindow", "87U2", None))
        self.feeder_combo_box.setItemText(52, _translate("MainWindow", "87U3", None))
        self.feeder_combo_box.setItemText(53, _translate("MainWindow", "89U1", None))
        self.feeder_combo_box.setItemText(54, _translate("MainWindow", "89U4", None))
        self.feeder_combo_box.setItemText(55, _translate("MainWindow", "8U1", None))
        self.feeder_combo_box.setItemText(56, _translate("MainWindow", "8U2", None))
        self.feeder_combo_box.setItemText(57, _translate("MainWindow", "90U4", None))
        self.feeder_combo_box.setItemText(58, _translate("MainWindow", "98U1", None))
        self.feeder_combo_box.setItemText(59, _translate("MainWindow", "98U3", None))
        self.feeder_combo_box.setItemText(60, _translate("MainWindow", "98U4", None))
        self.feeder_combo_box.setItemText(61, _translate("MainWindow", "AQUEDT", None))
        self.feeder_combo_box.setItemText(62, _translate("MainWindow", "BRCLIF", None))
        self.feeder_combo_box.setItemText(63, _translate("MainWindow", "BRCLIF1", None))
        self.feeder_combo_box.setItemText(64, _translate("MainWindow", "BRCLIF2", None))
        self.feeder_combo_box.setItemText(65, _translate("MainWindow", "BYRAM", None))
        self.feeder_combo_box.setItemText(66, _translate("MainWindow", "BYRAM1", None))
        self.feeder_combo_box.setItemText(67, _translate("MainWindow", "CHAPEL", None))
        self.feeder_combo_box.setItemText(68, _translate("MainWindow", "CORTLN", None))
        self.feeder_combo_box.setItemText(69, _translate("MainWindow", "CORTLT1", None))
        self.feeder_combo_box.setItemText(70, _translate("MainWindow", "CORTLT2", None))
        self.feeder_combo_box.setItemText(71, _translate("MainWindow", "CROTON", None))
        self.feeder_combo_box.setItemText(72, _translate("MainWindow", "CROTON1", None))
        self.feeder_combo_box.setItemText(73, _translate("MainWindow", "CROTON2", None))
        self.feeder_combo_box.setItemText(74, _translate("MainWindow", "CROWHL", None))
        self.feeder_combo_box.setItemText(75, _translate("MainWindow", "CROWHL1", None))
        self.feeder_combo_box.setItemText(76, _translate("MainWindow", "CROWHL2", None))
        self.feeder_combo_box.setItemText(77, _translate("MainWindow", "CROWHL3", None))
        self.feeder_combo_box.setItemText(78, _translate("MainWindow", "FURNDK", None))
        self.feeder_combo_box.setItemText(79, _translate("MainWindow", "FURNDK1", None))
        self.feeder_combo_box.setItemText(80, _translate("MainWindow", "FURNDK2", None))
        self.feeder_combo_box.setItemText(81, _translate("MainWindow", "HAMLTN1", None))
        self.feeder_combo_box.setItemText(82, _translate("MainWindow", "HAMLTN2", None))
        self.feeder_combo_box.setItemText(83, _translate("MainWindow", "HEATHC", None))
        self.feeder_combo_box.setItemText(84, _translate("MainWindow", "HEATHC1", None))
        self.feeder_combo_box.setItemText(85, _translate("MainWindow", "HEATHC2", None))
        self.feeder_combo_box.setItemText(86, _translate("MainWindow", "MTKISC", None))
        self.feeder_combo_box.setItemText(87, _translate("MainWindow", "MTKISC1", None))
        self.feeder_combo_box.setItemText(88, _translate("MainWindow", "MTKISC2", None))
        self.feeder_combo_box.setItemText(89, _translate("MainWindow", "NEWCAS", None))
        self.feeder_combo_box.setItemText(90, _translate("MainWindow", "NEWCAS1", None))
        self.feeder_combo_box.setItemText(91, _translate("MainWindow", "NEWCAS2", None))
        self.feeder_combo_box.setItemText(92, _translate("MainWindow", "PANAS", None))
        self.feeder_combo_box.setItemText(93, _translate("MainWindow", "PEEKSL", None))
        self.feeder_combo_box.setItemText(94, _translate("MainWindow", "PEEKSL1", None))
        self.feeder_combo_box.setItemText(95, _translate("MainWindow", "PEEKSL2", None))
        self.feeder_combo_box.setItemText(96, _translate("MainWindow", "PINEBR", None))
        self.feeder_combo_box.setItemText(97, _translate("MainWindow", "PINEBR1", None))
        self.feeder_combo_box.setItemText(98, _translate("MainWindow", "PINEBR2", None))
        self.feeder_combo_box.setItemText(99, _translate("MainWindow", "SD-37", None))
        self.feeder_combo_box.setItemText(100, _translate("MainWindow", "SPROUT", None))
        self.feeder_combo_box.setItemText(101, _translate("MainWindow", "SPROUT1", None))
        self.feeder_combo_box.setItemText(102, _translate("MainWindow", "TEATN", None))
        self.feeder_combo_box.setItemText(103, _translate("MainWindow", "TEATN1", None))
        self.feeder_combo_box.setItemText(104, _translate("MainWindow", "TEATN2", None))
        self.feeder_combo_box.setItemText(105, _translate("MainWindow", "WAMPUS2", None))
        self.feeder_combo_box.setItemText(106, _translate("MainWindow", "WHIPP", None))
        self.feeder_combo_box.setItemText(107, _translate("MainWindow", "WHIPP1", None))
        self.feeder_combo_box.setItemText(108, _translate("MainWindow", "WHIPP2", None))
        self.feeder_combo_box.setItemText(109, _translate("MainWindow", "WHITE", None))
        self.feeder_combo_box.setItemText(110, _translate("MainWindow", "WHITE1", None))
        self.feeder_combo_box.setItemText(111, _translate("MainWindow", "WHITE2", None))
        self.feeder_combo_box.setItemText(112, _translate("MainWindow", "WHITE3", None))
        self.feeder_combo_box.setItemText(113, _translate("MainWindow", "WINDML1", None))
        self.feeder_combo_box.setItemText(114, _translate("MainWindow", "WINDML2", None))
        self.feeder_combo_box.setItemText(115, _translate("MainWindow", "WNDMIL2", None))
        self.feeder_combo_box.setItemText(116, _translate("MainWindow", "WINGFT", None))
        self.lat_lon_line_edit.setText(_translate("MainWindow", "41.31032648    -73.91315804 ", None))
        self.ms_plate_line_edit.setText(_translate("MainWindow", "132-W", None))
        self.groupBox.setTitle(_translate("MainWindow", "Utility Assets", None))
        self.get_utility_assets_by_feeder.setText(_translate("MainWindow", "Get Utility Assets by Feeder", None))
        self.enable_asset_sort.setText(_translate("MainWindow", "sort ena", None))
        self.clear_utility_selection.setText(_translate("MainWindow", "reset", None))
        self.page_load_label.setText(_translate("MainWindow", "[]", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "ONT Collection", None))
        self.collect_onts_pushbutton.setText(_translate("MainWindow", "Collect", None))
        self.enable_collect_sort.setText(_translate("MainWindow", "sort ena", None))
        self.clear_collect_select.setText(_translate("MainWindow", "reset", None))
        self.clear_collection_pushbutton.setText(_translate("MainWindow", "Clear", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "ONTs", None))
        self.label_11.setText(_translate("MainWindow", "Lat, Lon", None))
        self.label_12.setText(_translate("MainWindow", "Radius", None))
        self.ont_lat_lon_line_edit.setText(_translate("MainWindow", "41.31032648    -73.91315804 ", None))
        self.ont_radius_line_edit.setText(_translate("MainWindow", "0.12", None))
        self.enable_ont_sort.setText(_translate("MainWindow", "sort ena", None))
        self.clear_ont_select.setText(_translate("MainWindow", "reset", None))
        self.ont_area_load_label.setText(_translate("MainWindow", "[]", None))
        self.get_onts_in_area.setText(_translate("MainWindow", "Get ONTs in Area", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Raw Alarms", None))
        self.get_raw_alarms_4_onts.setText(_translate("MainWindow", "Get RAW alarms for Selected ONTS", None))
        self.enable_raw_sort.setText(_translate("MainWindow", "sort ena", None))
        self.alarm_load_label.setText(_translate("MainWindow", "[]", None))
        self.filter_for_duration.setText(_translate("MainWindow", "Duration > 5", None))
        self.export_selected_alarms_pushbutton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Save the lines selected from the table below to the file name listed to the right or all lines if no lines are selected. </p></body></html>", None))
        self.export_selected_alarms_pushbutton.setText(_translate("MainWindow", "Export CSV", None))
        self.export_directory_line_edit.setText(_translate("MainWindow", "141_DOGWOOD_RD_raw_alarms.csv", None))
        self.assign_to_assets.setToolTip(_translate("MainWindow", "<html><head/><body><p>Assign this outage to the nearest asset and save it to the file named based on the work order. </p></body></html>", None))
        self.assign_to_assets.setText(_translate("MainWindow", "Export Assignments", None))
        self.restrict_to_timespan_checkbox.setText(_translate("MainWindow", "Restrict to timespan (+/- H)", None))
        self.time_span_window.setText(_translate("MainWindow", "24", None))
        self.restrict_to_radius_checkbox.setText(_translate("MainWindow", "Restrict to Radius", None))
        self.export_kml.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select some lines to export only those lines or deslect all lines to export a KML file of all the alarms in the tabel below. </p><p><br/></p></body></html>", None))
        self.export_kml.setText(_translate("MainWindow", "Export KML", None))
        self.stop_pushbutton.setText(_translate("MainWindow", "Interrupt", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "PONS Alarm File", None))
        self.mark_raw_events_pushbutton.setText(_translate("MainWindow", "Mark Raw Events", None))
        self.dump_raw_event_pushbutton.setToolTip(_translate("MainWindow", "Mark Raw Events first then Dump Raw Event", None))
        self.dump_raw_event_pushbutton.setText(_translate("MainWindow", "Dump Raw Events", None))
        self.find_alarm_files_bushbutton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Find the alarm files that have the ONT listed in the search box over the date range specified. </p></body></html>", None))
        self.find_alarm_files_bushbutton.setText(_translate("MainWindow", "Find Alarm File(s)", None))
        self.label_16.setText(_translate("MainWindow", "ONT Seatch String", None))
        self.ont_search_string_text.setText(_translate("MainWindow", "58458525", None))
        self.label_14.setText(_translate("MainWindow", "From", None))
        self.label_15.setText(_translate("MainWindow", "To", None))
        self.clear_raw_events_pushbutton.setText(_translate("MainWindow", "Clear Raw Events", None))
        self.label_13.setText(_translate("MainWindow", "Alarm File(s)", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences...", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

